### ISSUE TITLE
path to a bed file

### ISSUE THREAD

**Issue by chlangley** [AndreaGuarracino/readcombination#1]
Hello Andrea:
Thanks for sharing the PRDM9 motif/site bed file on the T2T Slack.
And thanks for putting up this GitHub with the info about meme:fimo and the matrices from Altemose et al.

I have no experience with motif annotation.  
After spending a while trying to work backwards from your bed file to fimo output from things like:
           `fimo --thresh 1.0E-4 --verbosity 1 PRDM9_motifs.human.txt CHM13_chr12_1_100000.fasta`
I have concluded I need a little help.
Please point me towards (show me) the method you advise to convert the fimo tsv to the simple bed file.

Thanks again.    Chuck

**Comment by AndreaGuarracino** [comment]
Hi @chlangley,
a way to get a `BED` file format from `fimo` output is something close to

`sed '1d'  fimo-output.tsv | sed '/^$/d' | awk -v OFS='\t' '{print($2,$3-1,$4,$1,$6,$5,$7,$8,$9)}' | bedtools sort > fimo-output.bed`
